### ISSUE TITLE
Doesn't work for japanese

### ISSUE THREAD

**Issue by languagemaniac** [Eltaurus-Lt/CourseDump2022#10]
Hi, I tried this with [this memrise course](https://app.memrise.com/course/45725/jlpt-n1-2000-vocabulary-words-japanese/) just for testing, but it looks like it doesn't recognize the japanese characters. Would be nice if you could add support for japanese, or other languages.

Thanks

**Comment by Eltaurus-Lt** [comment]
Could you please elaborate on the kind of problems you are experiencing?
I just downloaded the course you pointed out and didn't see anything wrong with it. Also, I downloaded all the official Japanese courses before that with no problems either.

**Comment by languagemaniac** [comment]
Sure, I get [this ](https://imgur.com/qWeeWyd) (link to imgur) in the csv.

edit: Looks like It's some kind of microsoft excel problem. I tried opening the same csv with openoffice and it does correctly display the japanese text, so no issues at all
