### ISSUE TITLE
Not downloading cards or audio

### ISSUE THREAD

**Issue by cstrife1** [Eltaurus-Lt/CourseDump2022#11]
https://app.memrise.com/course/365575/korean-pronunciation-skeleton/

Doesn't fill csv or download the media. I believe it's because it's different to most as there's only a FRONT (text) and audio, no back.

**Comment by Eltaurus-Lt** [comment]
> https://app.memrise.com/course/365575/korean-pronunciation-skeleton/
> 
> Doesn't fill csv or download the media. I believe it's because it's different to most as there's only a FRONT (text) and audio, no back.

You are right, this course has quite an unusual data structure. I've added support for audio files in the definition fields.
It seems to work for such cases now.
