### ISSUE TITLE
Not an issue but a feature suggestion

### ISSUE THREAD

**Issue by languagemaniac** [Eltaurus-Lt/CourseDump2022#19]
Hi, I'm trying to copy [this](https://app.memrise.com/course/548340/7-124/) course. I tried copying it but it doesn't seem to be able to copy the text that shows when you select the correct answer on the tests.

In short, this is an example of what I get when I dump the course:

愛犬, pet dog

What I would like to get:

愛犬, あいけん, pet dog

It's a total of 1281 words so noting down the readings (kana) manually would take me ages.

What I want to do is change this course's "direction", that is, put it back into memrise but in a way that it shows Kanji against Kana, and shows the english translation when I select the correct answer on the tests, which would help me prioritize learning the readings.

**Comment by Eltaurus-Lt** [comment]
Hey. I've added an additional setting to the extension, so [if you set](https://github.com/Eltaurus-Lt/CourseDump2022#settings) `EXTRA_INFO = true` before downloading the course, this should include the needed information as a separate spreadsheet column, after the tags.

**Comment by languagemaniac** [comment]
> Hey. I've added an additional setting to the extension, so [if you set](https://github.com/Eltaurus-Lt/CourseDump2022#settings) `EXTRA_INFO = true` before downloading the course, this should include the needed information as a separate spreadsheet column, after the tags.

Great thanks! I'll give it a try.

edit: Yep, works great, thanks so much!!

**Comment by Eltaurus-Lt** [comment]
You are most welcome)
