### ISSUE TITLE
How to download images as well?

### ISSUE THREAD

**Issue by yanrs17** [Eltaurus-Lt/CourseDump2022#22]
The extension is great, but seems it does not download images at the same time. What should I do for images? Like [this one](https://app.memrise.com/course/150927/car-logos-2/)? Thanks!

**Comment by Eltaurus-Lt** [comment]
Thank you/
I've added support for the images in the definition fields. Check out the new version!

**Comment by yanrs17** [comment]
Thanks! The one above works, but for some other courses it simply does not download any images: https://app.memrise.com/course/87549/constellations-nt/

I realized it is because the image is in the first place, then comes the explanation. In this case the extension cannot recognize the image and thus ignore the field.

**Comment by Eltaurus-Lt** [comment]
Here the images were stored in a different place, so I wrote another update to account for this kind of courses.

Because there is no way to know in advance, where else Memrise decides to stick images within its database, such cases have to be dealt with one by one as they are revealed. So, please tell, if there are any other courses the current version of the extension does not work with.

**Comment by yanrs17** [comment]
Thanks! For most courses here: https://app.memrise.com/courses/english/the-natural-world/ 
Most of these courses there have reverse cards (Word -> Image then Image -> Word). Then the reverse cards simply don't work.
But fortunately it is fine, I can simply remove the reverse cards later manually in .csv and add reverse cards in Anki.
But for those courses only have Image -> Word cards but no Word -> Image, then I cannot do anything about it.
But fortunately these courses are not a lot, the second one I found: https://app.memrise.com/course/149175/breeds-of-dogs-2/

**Comment by Eltaurus-Lt** [comment]
> Then the reverse cards simply don't work.

I'm not sure what kind of issue you are talking about. Everything seems fine to me. What kind of behavior are you expecting from the extension in this case?

> But for those courses only have Image -> Word cards but no Word -> Image, then I cannot do anything about it.

If you want Anki to test these questions both ways, you can simply import the data using the `Basic (and reversed card)` Note type.

**Comment by yanrs17** [comment]
LOL, you updated again and I did not realize that. The newest version seems to work in all cases. Thanks!
