### ISSUE TITLE
Feature Request: download attributes as well

### ISSUE THREAD

**Issue by miladklb** [Eltaurus-Lt/CourseDump2022#28]
Hello!
Thanks for the awesome work you have done!
I was wondering if it's possible to download attributes? It's not possible using turning EXTRA_INFO = true

**Comment by Eltaurus-Lt** [comment]
Thank you for the positive feedback!
Could you please provide an example of a course with the data you want to download?

**Comment by UtilityWorlds** [comment]
I think he is mentioning the attributes here:

<img width="266" alt="image" src="https://github.com/Eltaurus-Lt/CourseDump2022/assets/126215834/def0fdb7-d28e-4bd2-989e-44bb62709be8">

I need the attributes too. 
Could you add it?

**Comment by Eltaurus-Lt** [comment]
Which course is this from?
The ones I tested didn't have this field, so I need a link to see, where memrise stores this information.

**Comment by UtilityWorlds** [comment]
this is the link of the course:
https://app.memrise.com/course/686844/fluent-with-friends-s1e2/

**Comment by Eltaurus-Lt** [comment]
I've updated the script, so you can check out the new version.

The attributes are now stored in the same field as other extra data, and the download is controlled by the same `extra_info` setting. This is done so as not to overcomplicate the structure of `csv` files with too many different rarely-used fields. I expect the chance of a course having several types of extra data at the same time to be very low, but please feel free to notify me, if you encounter such a case and it causes you any problems.

Also note, that the settings (including the `extra_info`) are now accessed via a separate file. The details are in the readme:  https://github.com/Eltaurus-Lt/CourseDump2022#settings

**Comment by UtilityWorlds** [comment]
I've tried and it worked like a charm 😆

Thank you so much!
