### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by HQYang1979** [Eltaurus-Lt/CourseDump2022#31]
Could not download courses any more.
1) cannot retrieve word list
2) cannot download media.

![image](https://github.com/Eltaurus-Lt/CourseDump2022/assets/74698160/8b8a6d81-d874-4789-8b0c-0fd2a7b3aeea)

**Comment by Eltaurus-Lt** [comment]
The reason is that not so long ago Memrise completely changed how the site functions (again), so the old fetching requests do not work anymore.

I am looking into this, but it is likely that if there is a way of downloading data from the new site, it would require rewriting everything from scratch.

**Comment by HQYang1979** [comment]
Thank you very much, it helped me a lot already. Fortunately I've almost downloaded everything from Memrise. The thing about Memrise is its poor editability. Looking forward to your update though!

**Comment by Eltaurus-Lt** [comment]
Thank you for the positive feedback.
I updated the extension, so it should work now. Until the next change from Memrise at least :)

I tested the new version on several courses, but it is infeasible for me alone to cover every use case, so there still might be something that is not working as it used to. Please feel free to open new issues if you notice anything wrong with it.
