### ISSUE TITLE
Not fully downloading  media

### ISSUE THREAD

**Issue by moltovivo** [Eltaurus-Lt/CourseDump2022#41]
I tried on this deck and getting console errors, and  all the media is not downloaded. Console dump  below.
https://app.memrise.com/community/course/22128/who-painted-me-part-2/

modal-slides.js:115 Uncaught TypeError: t.hasOwn is not a function
    at t.exports (modal-slides.js:115:10)
    at 20.1 (memrise-bundle.js:50:11)
    at o (_prelude.js:1:1)
    at r (_prelude.js:1:1)
    at _prelude.js:1:1
t.exports @ modal-slides.js:115
20.1 @ memrise-bundle.js:50
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
Show 3 more frames
Show less
coursedump2022.js:80 course:  Who Painted Me? ~ Part 2
coursedump2022.js:81 about:  More famous artists of Western art history, most from the 20th century but not exclusively. Images are public domain, courtesy of Wikimedia commons. 
DW7 is assisting and has made enhancements. Course is now 4 times the size with different types of testing added after each Multimedia level to change the learning emphasis. See "What next?" for further study. Updated October 2015.
NB for important info about Community Courses see forum.mylittlewordland.com/d/8
coursedump2022.js:82 by:  Annajenta
coursedump2022.js:83 ava  https://static.memrise.com/img/100sqf/from/uploads/profiles/Annajenta_120202_0956_34.JPG
coursedump2022.js:84 icon  https://static.memrise.com/img/400sqf/from/uploads/course_photos/Kandinsky_1939_Composition-X.jpg
coursedump2022.js:85 number of levels:  12
coursedump2022.js:125 [who-painted-me-part-2] scanning level 1...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 2...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 3...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 400 (Bad Request)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 1
coursedump2022.js:125 [who-painted-me-part-2] scanning level 4...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 5...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 6...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 400 (Bad Request)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 1
coursedump2022.js:125 [who-painted-me-part-2] scanning level 7...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 8...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 9...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 400 (Bad Request)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 1
coursedump2022.js:125 [who-painted-me-part-2] scanning level 10...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 11...
coursedump2022.js:125 [who-painted-me-part-2] scanning level 12...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 400 (Bad Request)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 1
coursedump2022.js:125 [who-painted-me-part-2] scanning level 13...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 404 (Not Found)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 2
coursedump2022.js:125 [who-painted-me-part-2] scanning level 14...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 404 (Not Found)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 3
coursedump2022.js:125 [who-painted-me-part-2] scanning level 15...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 404 (Not Found)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 4
coursedump2022.js:125 [who-painted-me-part-2] scanning level 16...
coursedump2022.js:133 
        
        
       POST https://app.memrise.com/v1.19/learning_sessions/preview/ 404 (Not Found)
CourseDownload @ coursedump2022.js:133
await in CourseDownload (async)
(anonymous) @ coursedump2022.js:513
await in (anonymous) (async)
(anonymous) @ coursedump2022.js:517
Show 3 more frames
Show less
coursedump2022.js:160 TypeError: Cannot read properties of undefined (reading 'name')
coursedump2022.js:326 TypeError: Cannot read properties of undefined (reading 'map')
    at CourseDownload (coursedump2022.js:166:24)
    at async coursedump2022.js:513:7
coursedump2022.js:327 Level does not exist or has no learnable words. Level skip count: 5
coursedump2022.js:398 [who-painted-me-part-2] media files found: 31
coursedump2022.js:455 2.86% media queued
coursedump2022.js:455 5.71% media queued
coursedump2022.js:455 8.57% media queued
coursedump2022.js:455 11.43% media queued
coursedump2022.js:455 14.29% media queued
coursedump2022.js:455 17.14% media queued
coursedump2022.js:455 20% media queued
coursedump2022.js:455 22.86% media queued
coursedump2022.js:455 25.71% media queued
coursedump2022.js:455 28.57% media queued
coursedump2022.js:455 31.43% media queued
coursedump2022.js:455 34.29% media queued
coursedump2022.js:455 37.14% media queued
coursedump2022.js:455 40% media queued
coursedump2022.js:455 42.86% media queued
coursedump2022.js:455 45.71% media queued
coursedump2022.js:455 48.57% media queued
coursedump2022.js:455 51.43% media queued
coursedump2022.js:455 54.29% media queued
coursedump2022.js:455 57.14% media queued
coursedump2022.js:455 60% media queued
coursedump2022.js:455 62.86% media queued
coursedump2022.js:455 65.71% media queued
coursedump2022.js:455 68.57% media queued
coursedump2022.js:455 71.43% media queued
coursedump2022.js:455 74.29% media queued
coursedump2022.js:455 77.14% media queued
coursedump2022.js:455 80% media queued
coursedump2022.js:455 82.86% media queued
coursedump2022.js:455 85.71% media queued
coursedump2022.js:455 88.57% media queued
coursedump2022.js:455 91.43% media queued
coursedump2022.js:455 94.29% media queued
coursedump2022.js:455 97.14% media queued
coursedump2022.js:455 100% media queued

**Comment by Eltaurus-Lt** [comment]
The errors you are seeing are from Memrise "Media" levels (3, 6, 9, and 12 for this course) - you can simply ignore those. The script is not supposed to download anything from them, because they do not actually have any tabular learning data.

The images contained in all the other levels seem to be downloading just fine (there are only 31 unique images in total, I went and rechecked each manually), or does it work anything differently for you?
