### ISSUE TITLE
bug in memrise community course #136, learnable field blank leaving card invalid in anki

### ISSUE THREAD

**Issue by whereistimbo** [Eltaurus-Lt/CourseDump2022#64]
the course in question has media file (sound) as multiple choice:
<img width="1194" alt="Screen Shot 2024-07-07 at 20 22 40" src="https://github.com/Eltaurus-Lt/CourseDump2022/assets/47355692/5c6518f1-7048-4918-83f3-750271094ae5">

the resulting downloaded csv when opened in libreoffice:
![ciu0akwg](https://github.com/Eltaurus-Lt/CourseDump2022/assets/47355692/233441ac-2229-441f-89fb-5d961f470272)

course url https://community-courses.memrise.com/community/course/136/audio-beginners-greek-00-alphabet-letters/
my downloaded course: 
[audio-beginners-greek-00-alphabet-letters by somada141 [136].zip](https://github.com/user-attachments/files/16119463/audio-beginners-greek-00-alphabet-letters.by.somada141.136.zip)

**Comment by Eltaurus-Lt** [comment]
It looks like you are using an older version of the extension (v8.6 I presume?). Can you try updating to v9.0 and downloading this course again? At least I didn't encounter any such problems while downloading this course with it:

![image](https://github.com/Eltaurus-Lt/CourseDump2022/assets/93875472/33d6a15d-b436-4c1d-8e8d-f8fd91825863)

**Comment by whereistimbo** [comment]
Thank you for your help! You are right that I haven't updated the extension, so updating the extension solve the issue.  I've had another issue when using the imported course in Anki, but that would be another issue to open.
