### ISSUE TITLE
error when downloading memrise community course #700007 "File download request from a conflicting tab received and rejected"

### ISSUE THREAD

**Issue by whereistimbo** [Eltaurus-Lt/CourseDump2022#68]
![screenshot](https://github.com/user-attachments/assets/1bd12f00-8d07-41f0-bf12-05be9d0508d6)

Extension version: 9.1

Course url: https://community-courses.memrise.com/community/course/700007/learn-management/

I'm so sorry if this came as too demanding.
Thanks in advance.

**Comment by Eltaurus-Lt** [comment]
Is this a recurring issue? Does it occur if you restart Chrome and try downloading the course again? Does it happen with other courses as well?

If it does happen again after a restart, I'd like to take a look at the logs. Can you post them here? (you'll need to open Chrome Extension Manager, click on the "service worker" link for the extension, and make a screenshot or copy the text from its console)
![image](https://github.com/user-attachments/assets/68cf1294-e36f-423e-a183-e03226d915d5)

**Comment by whereistimbo** [comment]
I'm sorry I cannot reproduce the issue because it already worked as of now 😅, I have tried multiple times before and it didn't work, but weirdly enough, after I enabled "Developer Mode" and viewed the logs, it worked without any issue.
![screenshot2](https://github.com/user-attachments/assets/569da392-e876-4418-897d-62ef0b924d49)

Thanks for your help as always!
